name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main  # Trigger on push to main branch (you can change this)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-cloudfront-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    - name: Copy index.html to S3
      run: aws s3 cp src/index.html s3://$S3_BUCKET/index.html
    
    - name: Copy output.css to S3
      run: aws s3 cp src/output.css s3://$S3_BUCKET/output.css

    # Step 3: Create a CloudFront invalidation
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
