name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: YOUR_AWS_REGION

    - name: Copy index.html to S3
      run: aws s3 cp src/index.html s3://${{ secrets.S3_BUCKET }}/index.html
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}

    - name: Copy output.css to S3
      run: aws s3 cp src/output.css s3://${{ secrets.S3_BUCKET }}/output.css
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}

    - name: Create CloudFront Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
